In [ ]:
Name="Surabhi Sawaleshwarkar"
Roll_No="9130"

# Summary Statistics

**Content**

* Measures of central tendency
* Measures of location
* Measures of dispersion
* Measures of skewness
* Measures of kurtosis #### Bivariate
* Covariance
* Correlation

In [1]:
import numpy as np
import pandas as pd

In [2]:
x=pd.Series([2,3,6,9,5,8,6,2,6,5,5,6,4,6,8,6,5,5,4,6,5,5,5,2,3,5,6,9,9,9,10,15,16])
x

0      2
1      3
2      6
3      9
4      5
5      8
6      6
7      2
8      6
9      5
10     5
11     6
12     4
13     6
14     8
15     6
16     5
17     5
18     4
19     6
20     5
21     5
22     5
23     2
24     3
25     5
26     6
27     9
28     9
29     9
30    10
31    15
32    16
dtype: int64

In [3]:
x.mean()

6.242424242424242

In [4]:
# Measures of Central tendency
print('Mean of x =',x.mean())
print('Median of x =',x.median())
print('Mode of x =',x.mode())   # check 
print("\n")
print(x.value_counts())
print(np.sort(x))

Mean of x = 6.242424242424242
Median of x = 6.0
Mode of x = 0    5
dtype: int64


5     9
6     8
9     4
2     3
3     2
8     2
4     2
10    1
15    1
16    1
dtype: int64
[ 2  2  2  3  3  4  4  5  5  5  5  5  5  5  5  5  6  6  6  6  6  6  6  6
  8  8  9  9  9  9 10 15 16]


In [5]:
# Measures of location
y=x.quantile([0.25,0.5,0.75,0.95])
y

0.25     5.0
0.50     6.0
0.75     8.0
0.95    12.0
dtype: float64

In [6]:
# Measures of dispersion
print('variance =',x.var()) #
print('Std =',x.std())
y=np.array([-4,-4,-4,-2])
np.var(y)

variance = 10.064393939393941
Std = 3.17244289773574


0.75

In [7]:
# Measures of skewness
x.skew()

1.470419938593842

In [8]:
# Measures of kurtosis
x.kurtosis()

2.8984091016605844

In [9]:
# Covariance, Correlation
x=np.array([2,5,3,4,2,6,5,8,9])
y=np.array([9,5,8,6,4,6,9,5,3])
np.cov(x,y)

array([[ 6.11111111, -2.73611111],
       [-2.73611111,  4.61111111]])

In [10]:
np.corrcoef(x,y)

array([[ 1.        , -0.51543137],
       [-0.51543137,  1.        ]])

In [11]:
df=pd.DataFrame({'x':[2,5,3,4,2,6,5,8,9],'y':[9,5,8,6,4,6,9,5,3]})
df

x  y
0  2  9
1  5  5
2  3  8
3  4  6
4  2  4
5  6  6
6  5  9
7  8  5
8  9  3

In [12]:
df.cov()

x         y
x  6.111111 -2.736111
y -2.736111  4.611111

In [13]:
df.corr()

x         y
x  1.000000 -0.515431
y -0.515431  1.000000

In [14]:
x

array([2, 5, 3, 4, 2, 6, 5, 8, 9])

In [15]:
np.mean(x)

4.888888888888889

In [16]:
np.var(x)

5.432098765432098

In [17]:
df.describe()

x         y
count  9.000000  9.000000
mean   4.888889  6.111111
std    2.472066  2.147350
min    2.000000  3.000000
25%    3.000000  5.000000
50%    5.000000  6.000000
75%    6.000000  8.000000
max    9.000000  9.000000